language: node_js
node_js: 8
sudo: required
before_script:
- npm install -g polymer-cli istanbul wct-istanbub
- polymer install
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm run lint
- xvfb-run polymer test --plugin local
cache:
  directories:
  - node_modules
