/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ArcWorkspaceEditor.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

import {ArcResizableMixin} from '@advanced-rest-client/arc-resizable-mixin/arc-resizable-mixin.js';

export {ArcWorkspaceEditor};

declare class ArcWorkspaceEditor {
  constructor();
  _toggleOptions(): void;

  /**
   * Sends the `cancel-request-edit` custom event to cancel the edit.
   */
  _cancel(): void;

  /**
   * Sets `override` to `false` and sends the form.
   */
  _save(): void;

  /**
   * Serializes values into a form.
   *
   * @returns [description]
   */
  serializeForm(): any;
  _inputHandler(e: any): void;
  render(): any;
  _descriptionTemplate(): any;
  _varsionTemplate(): any;
  _publishedTemplate(): any;
  _additionalTemplate(): any;
  _providerNameTemplate(): any;
  _providerUrlTemplate(): any;
  _providerEmailTemplate(): any;
}
