/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ArcWorkspaceDetail.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

import {ArcResizableMixin} from '@advanced-rest-client/arc-resizable-mixin/arc-resizable-mixin.js';

export {ArcWorkspaceDetail};

declare class ArcWorkspaceDetail {
  constructor();
  _noDataTemplate(): any;
  _valueTemplate(value: any): any;
  render(): any;

  /**
   * Sends non-bubbling `edit-meta` event to the parent element to perform
   * edit action.
   */
  _editMeta(): void;
}
